### ISSUE TITLE
[Bug]: opentelemetry-datadog does not compile with otel 0.29

### ISSUE THREAD

**Issue by pimeys** [open-telemetry/opentelemetry-rust-contrib#212]
### What happened?

After getting a renovate update to opentelemetry 0.29, we realized the opentelemetry-datadog crate did not get an update to work with the new version.

### API Version

N/A

### SDK Version

0.29

### Relevant log output

```shell
error[E0599]: the method `with_batch_config` exists for struct `BatchSpanProcessorBuilder<DatadogExporter>`, but its trait bounds were not satisfied
Error:    --> api/src/runtime/std/tracing.rs:112:14
    |
111 |           let batch_span_processor = BatchSpanProcessor::builder(exporter)
    |  ____________________________________-
112 | |             .with_batch_config(
    | |             -^^^^^^^^^^^^^^^^^ method cannot be called on `BatchSpanProcessorBuilder<DatadogExporter>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
```
