### ISSUE TITLE
[Bug]: opentelemetry-aws types do not compile with otel 0.29

### ISSUE THREAD

**Issue by pimeys** [open-telemetry/opentelemetry-rust-contrib#211]
### What happened?

After getting a renovate update to our repository to update otel crates from 0.28 to 0.29. The opentelemetry-aws crate did not get an update, and we're now stuck with a failing build.

### API Version

N/A

### SDK Version

0.29.0

### What component are you working with?

opentelemetry-aws

### Relevant log output

```shell
error[E0277]: the trait bound `XrayPropagator: TextMapPropagator` is not satisfied
   --> gateway/src/telemetry.rs:139:26
    |
139 |         propagators.push(Box::new(XrayPropagator::default()));
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `TextMapPropagator` is not implemented for `XrayPropagator`
    |
note: there are multiple different versions of crate `opentelemetry` in the dependency graph
```

**Comment by cijothomas** [comment]
@jj22ee Hi can you help upgrading `aws` crate to 0.29 from upstream?

**Comment by gruebel** [comment]
@cijothomas you can assign me. I already started working on it and will be done a bit later today

**Comment by cijothomas** [comment]
@gruebel There is a PR opened for it : https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/219

**Comment by gruebel** [comment]
Gotcha, will review the PR instead 😄

**Comment by gruebel** [comment]
@cijothomas can you close this? done via #219
