### PR TITLE
chore: update Datadog to OTel 0.29

### LINKED ISSUE #212: [Bug]: opentelemetry-datadog does not compile with otel 0.29
### What happened?

After getting a renovate update to opentelemetry 0.29, we realized the opentelemetry-datadog crate did not get an update to work with the new version.

### API Version

N/A

### SDK Version

0.29

### What component are you working with?

_No response_

### Relevant log output

```shell
error[E0599]: the method `with_batch_config` exists for struct `BatchSpanProcessorBuilder<DatadogExporter>`, but its trait bounds were not satisfied
Error:    --> api/src/runtime/std/tracing.rs:112:14
    |
111 |           let batch_span_processor = BatchSpanProcessor::builder(exporter)
    |  ____________________________________-
112 | |             .with_batch_config(
    | |             -^^^^^^^^^^^^^^^^^ method cannot be called on `BatchSpanProcessorBuilder<DatadogExporter>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
```

### PR DESCRIPTION
**Pull request by gruebel**
Fixes #212 

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by gruebel** [comment]
> cargo-machete is rightly spotting that we have unused dependencies! Would be nice to get it added to main repo CI too!

Sure, I can add it to main repo too.
